version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::504565521825:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-FZXNBGQBKYF7"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::504565521825:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-9FDD2RFA2GBR"
cloudformation_execution_role = "arn:aws:iam::504565521825:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-Y2QRIDHZS6C9"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1rtmbhayr712z"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::504565521825:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-LJXIJQ3LW5CF"
cloudformation_execution_role = "arn:aws:iam::504565521825:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-366451V25GR"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-125oi0f2cow1a"
image_repository = ""
region = "us-east-1"
